GET http://3.91.155.146:5000/

###

POST http://3.91.155.146:5000/ HTTP/1.1
Content-Type: application/json

{
    "brightness": "0.5",
    "red": "255",
    "green": "0",
    "blue": "0",
    "frequency": "2",
    "area": "1"
}

###

POST http://3.91.155.146:5000/ HTTP/1.1
Content-Type: application/json

{
  "1": {
    "area": 0,
    "blue": 0,
    "brightness": "0.5",
    "frequency": 0,
    "green": 0,
    "red": 255
  },
  "2": {
    "area": 0,
    "blue": 0,
    "brightness": 0,
    "frequency": 0,
    "green": 255,
    "red": 0
  },
  "3": {
    "area": 0,
    "blue": 255,
    "brightness": 0.1,
    "frequency": 0,
    "green": 100,
    "red": 0
  },
  "4": {
    "area": 0,
    "blue": 255,
    "brightness": 0,
    "frequency": 0,
    "green": 0,
    "red": 128
  }
}